name: Build and Push to Aliyun ACR

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Aliyun ACR
        uses: docker/login-action@v3
        with:
          registry: crpi-f8e89bkxtt441m31.cn-qingdao.personal.cr.aliyuncs.com
          username: aliyun7010727154
          password: well4771

      # 关键：这里 只使用根目录 Dockerfile，不指定任何文件！
      - name: Build Docker image
        run: |
          docker build -t myapp .

      - name: Tag image
        run: |
          docker tag myapp crpi-f8e89bkxtt441m31.cn-qingdao.personal.cr.aliyuncs.com/neomao/prompthub:latest

      - name: Push to Aliyun ACR
        run: |
          docker push crpi-f8e89bkxtt441m31.cn-qingdao.personal.cr.aliyuncs.com/neomao/prompthub:latest
