name: Build and Push to Aliyun ACR

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 登录阿里云镜像仓库
      - name: Login to Aliyun ACR
        uses: docker/login-action@v3
        with:
          registry: crpi-f8e89bkxtt441m31.cn-qingdao.personal.cr.aliyuncs.com
          username: aliyun7010727154
          password: well4771

      # 构建 Docker 镜像
      - name: Build Docker image
        run: |
          docker build -t myapp .

      # 打标签（必须和你的仓库匹配）
      - name: Tag image
        run: |
          docker tag myapp crpi-f8e89bkxtt441m31.cn-qingdao.personal.cr.aliyuncs.com/prompthub:latest

      # 推送到阿里云
      - name: Push to Aliyun ACR
        run: |
          docker push crpi-f8e89bkxtt441m31.cn-qingdao.personal.cr.aliyuncs.com/prompthub:latest
